nav:
  Home: /
  Archives: /archives/
  Imprint: /imprint/

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/favicon.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.png
        gravatar: false
      android:
        url: /images/favicon.png
        gravator: false
      apple:
        url: /images/favicon.png
        gravator: false
    social_links:
        github: https://github.com/aerben
        linkedin: https://www.linkedin.com/in/alexander-erben-25464713a/
        xing: https://www.xing.com/profile/Alexander_Erben4
    show_all_posts: false
    post_count: 10
    highlight: monokai


# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-109898944-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
